# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Packages', path: 'menu', url: 'packages.html'}
- {name: 'Blog', path: 'menu', url: 'blog.html'}
- {name: 'Learn', path: 'menu', url: 'learn.html'}
- {name: 'Help', path: 'menu', url: 'help.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
