# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Packages', path: 'menu', url: 'packages.html'}
- {name: 'Updates', path: 'menu', url: 'updates.html'}
- {name: 'Learn', path: 'menu', url: 'learn.html'}
- {name: 'Help', path: 'menu', url: 'help.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'
