on:
  push:
    branches: master
  schedule:
    - cron:  '0 0 * * *'

name: news

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"

      - name: Deploy package
        run: |
          source("build_news.R")
          build_news(outfile = "menu/updates.md")
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update news
          file_pattern: menu/updates.md

